server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

  server:
    password: "${LAVALINK_SERVER_PASSWORD:change_me}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED

  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: ${SPOTIFY_ENABLED:false}
      applemusic: false
      deezer: false
      yandexmusic: ${YANDEX_MUSIC_ENABLED:false}
      flowerytts: false
      youtube: false
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    lyrics-sources:
      spotify: false
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    spotify:
      clientId: "${SPOTIFY_CLIENT_ID:}"
      clientSecret: "${SPOTIFY_CLIENT_SECRET:}"
      countryCode: "EE"
      playlistLoadLimit: 6
      albumLoadLimit: 6
      resolveArtistsInSearch: true
    yandexmusic:
      accessToken: "${YANDEX_MUSIC_TOKEN:}"
      playlistLoadLimit: 3
      albumLoadLimit: 3
      artistLoadLimit: 2

logging:
  level:
    root: INFO
    lavalink: INFO
